apiVersion: skaffold/v2beta4
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: ptadros/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
          - '**/*.css'
          - '**/*.html'
    - image: ptadros/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
    - image: ptadros/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
deploy:
  kubectl:
    manifests:
      - k8s/client-deploy.yaml
      - k8s/server-deploy.yaml
      - k8s/worker-deploy.yaml
      - k8s/server-cluster-ip-service.yaml
      - k8s/client-cluster-ip-service.yaml