apiVersion: skaffold/v2beta4
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: ptadros/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
          - '**/*.css'
          - '**/*.html'

deploy:
  kubectl:
    manifests:
      - k8s/client-deploy.yaml